package gl;

//comment
import java.util.concurrent.TimeUnit;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import gl.Circle;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Joseph
 */
public class gaugeForm extends javax.swing.JFrame {

    /**
     * Creates new form gaugeForm
     */
    
    // x is RPM, will change in the future.
    int x = 0;
    double speedNum = 0;
    int boost = 0;
    int currentGear = 1;
    String gearIncrease;
    String gearDecrease;
    String speedIncrease;
    String speedDecrease;
    String rpmIncrease;
    String rpmDecrease;
    String boostIncrease;
    String boostDecrease;
    boolean isEconomic;
    public gaugeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        throttleButton = new javax.swing.JButton();
        rpm = new javax.swing.JLabel();
        vtecdisplay = new javax.swing.JLabel();
        boostLabel = new javax.swing.JLabel();
        psiLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        speed = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        currentGearLabel = new javax.swing.JLabel();
        gearNumber = new javax.swing.JLabel();
        shiftUpButton = new javax.swing.JButton();
        shiftDownButton = new javax.swing.JButton();
        mode = new javax.swing.JButton();
        shiftTell = new javax.swing.JLabel();
        checkShiftLabel = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        throttleButton.setText("Throttle");
        throttleButton.setToolTipText("Accelerate");
        throttleButton.setEnabled(false);
        throttleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                throttleButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                throttleButtonMouseReleased(evt);
            }
        });

        rpm.setText("RPM");
        rpm.setToolTipText("Engine Speed measured in rotations per minute");

        boostLabel.setText("Boost");
        boostLabel.setToolTipText("Turbo pressure");
        boostLabel.setName("Boost"); // NOI18N

        psiLabel.setText("PSI");
        psiLabel.setToolTipText("(Pounds per square inch)");

        startButton.setText("Start");
        startButton.setToolTipText("Start car");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        speed.setText("MPH");
        speed.setToolTipText("Speed in Miles Per Hour");

        jLabel3.setText("Speedometer");
        jLabel3.setToolTipText("Moving speed of the car");

        jLabel4.setText("Tachometer");
        jLabel4.setToolTipText("Engine Speed measured in rotations per minute");

        currentGearLabel.setText("Current Gear");
        currentGearLabel.setToolTipText("Determines moving speed (MPH) and engine speed (RPM)");

        gearNumber.setText("1");
        gearNumber.setToolTipText("Determines moving speed (MPH) and engine speed (RPM)");

        shiftUpButton.setText("Shift up");
        shiftUpButton.setToolTipText("Change gear up (go faster)");
        shiftUpButton.setEnabled(false);
        shiftUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shiftUpButtonMouseClicked(evt);
            }
        });

        shiftDownButton.setText("Shift Down");
        shiftDownButton.setEnabled(false);
        shiftDownButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shiftDownButtonMouseClicked(evt);
            }
        });

        mode.setText("Economic");
        mode.setEnabled(false);
        mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeActionPerformed(evt);
            }
        });

        shiftTell.setText("                   ");

        checkShiftLabel.setText("Shift");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(vtecdisplay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gearNumber)
                                .addGap(189, 189, 189))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(startButton)
                                .addGap(18, 18, 18)
                                .addComponent(shiftUpButton)
                                .addGap(18, 18, 18)
                                .addComponent(shiftDownButton)
                                .addGap(13, 13, 13)))
                        .addComponent(throttleButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rpm)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(speed))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(currentGearLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addGap(50, 50, 50)))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shiftTell)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(psiLabel)
                            .addComponent(boostLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(checkShiftLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mode, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(mode)
                .addGap(18, 18, 18)
                .addComponent(shiftTell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(checkShiftLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(currentGearLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vtecdisplay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rpm)
                            .addComponent(speed)))
                    .addComponent(gearNumber))
                .addGap(58, 58, 58)
                .addComponent(boostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(psiLabel)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(throttleButton)
                    .addComponent(startButton)
                    .addComponent(shiftUpButton)
                    .addComponent(shiftDownButton))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private boolean mouseDown = false;
    private void throttleButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_throttleButtonMousePressed
        // TODO add your handling code here:
        //--------------->>>>>>>>>>> when mouse is clicked in.
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
        mouseDown = true;
        initThread();
        
    }
    }//GEN-LAST:event_throttleButtonMousePressed

    private void throttleButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_throttleButtonMouseReleased
        // TODO add your handling code here:
        //---------------->>>>>>>>>> when mouse is released
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
        mouseDown = false;
        //initThread();
    }
    }//GEN-LAST:event_throttleButtonMouseReleased

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        // ----------->>>>>>>>>>> initialize values
        x=800;
        boost = -25;
        speed.setText("0 MPH");
        psiLabel.setText("-25 PSI");
        boostLabel.setText("Vacuum");
        rpm.setText("800 RPM");
        mode.setEnabled(true);
        throttleButton.setEnabled(true);
        shiftUpButton.setEnabled(true);
        shiftDownButton.setEnabled(true);
        startButton.setEnabled(false);
        isEconomic = true;
    }//GEN-LAST:event_startButtonActionPerformed

    private void modeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeActionPerformed
        // TODO add your handling code here:
        if(isEconomic)
        {
            isEconomic = false;
            mode.setText("Performance");
        }
        else
        {
            isEconomic = true;
            mode.setText("Economic");
        }
    }//GEN-LAST:event_modeActionPerformed

    private void shiftUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shiftUpButtonMouseClicked
        // TODO add your handling code here:
        // Max gear is 6
        checkShift(x,isEconomic);
        if (currentGear <= 5){
            x-=1000;
            currentGear+=1;
            gearIncrease=Integer.toString(currentGear);
            gearNumber.setText(gearIncrease);
        }
        
    }//GEN-LAST:event_shiftUpButtonMouseClicked

    private void shiftDownButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shiftDownButtonMouseClicked
        // TODO add your handling code here:
        if (currentGear >= 2){
           x+=1000;
           currentGear-=1;
           gearDecrease=Integer.toString(currentGear);
           gearNumber.setText(gearDecrease);
       }
       
        
    }//GEN-LAST:event_shiftDownButtonMouseClicked


private boolean isRunning = false;
private synchronized boolean checkAndMark() {
    if (isRunning) return false;
    isRunning = true;
    return true;
}


// creates a thread in run time
private void initThread() {
    if (checkAndMark()) {
        new Thread() {
            public void run() {
                do {
                    //sleeps the system, so that we dont build the values too fast
                    goToSleep(30);
                    
                    // checks to display vtec
                    x = isVtec(x);
                    // checks rev limit, 
                    x = isRevLimit(x);
                    
                    // increment speed and display
                   if ((currentGear == 1) && (speedNum < 45)){
                    speedNum=speedNum+.5;
                    speedIncrease = Double.toString(speedNum);
                    speed.setText(speedIncrease + " MPH");
                   }
                   else if ((currentGear == 2) && (speedNum < 60)){
                    speedNum=speedNum+.5;
                    speedIncrease = Double.toString(speedNum);
                    speed.setText(speedIncrease + " MPH");
                   }
                    
                    // RPM increase
                    x+=100;        
                    rpmIncrease = Integer.toString(x);
                    rpm.setText(rpmIncrease + " RPM");
                    
                    //increase boost with a limit of 20
                    boost++;
                    boostIncrease = Integer.toString(boost);
                    psiLabel.setText(boostIncrease + " PSI");
                    
                    isBoost(boost);
                    isVacuum(boost);
                    
                    boost = isBoostLimit(boost);
                    
                    shiftTell(x);
                    
                    
                } while (mouseDown);
                isRunning = false;
                
                // once the mouse is released, this loop is entered.
                    do {
                        //sleep so it doesn't decrease topo quickly
                        goToSleep(30);
                        
                        //decrement the RPM
                        x-=50;
                        // decrease the RPM
                        rpmDecrease = Integer.toString(x);
                        rpm.setText(rpmDecrease + " RPM");
                        
                        
                        // decrease speed
                        speedNum=speedNum - .5;
                        speedDecrease = Double.toString(speedNum);
                        speed.setText(speedDecrease + " MPH");
                        
                        // to synchronize, forces speed to only have a min value of 0
                        if(speedNum < 0){
                            speedNum = 0;
                            speedDecrease = Double.toString(speedNum);
                            speed.setText(speedDecrease + " MPH");
                        }
                        
                        
                        
                        //vtec remove once dropped out of 5000
                        if (x < 5000)
                            vtecdisplay.setText("");
                      
                        // minimum RPM is 800
                        if (x <= 800) {
                            x=800;
                            rpmDecrease = Integer.toString(x);
                            rpm.setText(rpmDecrease + " RPM");
                        } 
                        
                        // decrement boost, only allow for -25
                        boost--;
                        boostDecrease = Integer.toString(boost);
                        psiLabel.setText(boostDecrease + " PSI");
                        isBoost(boost);
                        isVacuum(boost);
                        boost = isBoostLimitNeg(boost);
                        
                        shiftTell(x);
                        //disable the loop once all of the parameters have been met.
                        if (boost <= -25 && speedNum <= 0 && x <= 800){
                               
                        break;
                    }
                        
                    }while (mouseDown == false);
                
                  
            }
        }.start();
    }
}


private void goToSleep(int x){
    try {
        Thread.sleep(x);                //1000 milliseconds is one second.
    } catch (InterruptedException ex) {
        Thread.currentThread().interrupt();
    }
}

private void revUp(){

    
}
private void isBoost(int x){
    if (boost > 0){
        boostLabel.setText("Boost");
    }
}
private void isVacuum(int x){
    if (boost < 0){
        boostLabel.setText("Vacuum");
    }
}
private int isBoostLimit(int x){
    if (x > 20){
        x=20;
        psiLabel.setText("25 PSI");
    }
    return x;
}
private int isBoostLimitNeg(int x){
    if (x < -25){
        x = -25;
        psiLabel.setText("-25 PSI");
    }
    return x;
}
private int isRevLimit(int x){
    if (x > 9100) {
        x = 9100;
        rpm.setText("9100 RPM");
        goToSleep(50);
    }
    return x;
}

public int isVtec(int x){
    if (x > 5000) {
        vtecdisplay.setText("VTEC!");
        //x += 4;
    }
    return x;
}

public void shiftTell(int x)
{
    if(!isEconomic)
    {
        if(x > 9000)
        {
            shiftTell.setText("Shift Up");
        }
        else
            shiftTell.setText("");
    }    
    else
    {
        if(x > 2500)
        {
            shiftTell.setText("Shift Up");
        }
        else
            shiftTell.setText("");
    }
}

private void checkShift(int x, boolean eco){
    if(x > 1800 && x < 2500 && eco)
    checkShiftLabel.setText("Good economic shift!");
    else if(x > 8500 && x < 9200 && !eco)
    checkShiftLabel.setText("Good performance shift!");

}
    
private void increment(int x){
    
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gaugeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gaugeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gaugeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gaugeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gaugeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boostLabel;
    private javax.swing.JLabel checkShiftLabel;
    private javax.swing.JLabel currentGearLabel;
    private javax.swing.JLabel gearNumber;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton mode;
    private javax.swing.JLabel psiLabel;
    private javax.swing.JLabel rpm;
    private javax.swing.JButton shiftDownButton;
    private javax.swing.JLabel shiftTell;
    private javax.swing.JButton shiftUpButton;
    private javax.swing.JLabel speed;
    private javax.swing.JButton startButton;
    private javax.swing.JButton throttleButton;
    private javax.swing.JLabel vtecdisplay;
    // End of variables declaration//GEN-END:variables
}
